# Generated by Django 5.0 on 2023-12-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleador',
            options={'permissions': [('subida_documentos', 'Puede subir documentos')]},
        ),
    ]
